const eventRegistry = {
    lifecycle: ['session:start', 'session:move', 'session:end', 'session:cancel', 'fingers:change', 'gesture:start', 'gesture:update', 'gesture:transition', 'gesture:commit', 'gesture:end', 'gesture:cancel', 'input:ignored'],
    tap: ['tap', 'tap:1x', 'tap:2x', 'tap:3x', 'tap:sequence', 'tap:multi'],
    press: ['press', 'press:start', 'press:move', 'press:end', 'press:cancel'],
    pan: ['pan:start', 'pan', 'pan:end'],
    swipe: swipeRegistryEvents(),
    pinch: transformRegistryEvents('pinch', ['in', 'out']),
    rotate: transformRegistryEvents('rotate', ['cw', 'ccw']),
    path: ['path:start', 'path', 'path:end'],
    circle: circleRegistryEvents(),
    arc: arcRegistryEvents(),
    rolling: rollingRegistryEvents(),
    modifier: ['tap:mod', 'pan:mod:start', 'pan:mod', 'pan:mod:end'],
    pressure: ['pressure:change'],
    wheel: ['wheel', 'wheel:zoom']
};

const eventNames = Object.keys(eventRegistry).reduce((out, group) => out.concat(eventRegistry[group]), []);
const recognizerNames = ['tap', 'press', 'pan', 'swipe', 'pinch', 'rotate', 'path', 'rolling', 'modifier', 'pressure', 'wheel'];
const activatableRecognizers = listSet(recognizerNames);
const additiveEventTypes = {
    'session:start': true,
    'session:move': true,
    'session:end': true,
    'session:cancel': true,
    'fingers:change': true,
    'gesture:start': true,
    'gesture:update': true,
    'gesture:transition': true,
    'gesture:commit': true,
    'gesture:end': true,
    'gesture:cancel': true,
    'input:ignored': true,
    'tap:sequence': true,
    'press:start': true,
    'swipe:intent': true,
    'swipe:intent:left': true,
    'swipe:intent:right': true,
    'swipe:intent:up': true,
    'swipe:intent:down': true,
    'press:move': true,
    'press:end': true,
    'press:cancel': true,
    'pan:start': true,
    pan: true,
    'pan:end': true,
    'pinch:start': true,
    pinch: true,
    'pinch:end': true,
    'pinch:in': true,
    'pinch:out': true,
    'pinch:mod:start': true,
    'pinch:mod': true,
    'pinch:mod:end': true,
    'pinch:mod:in': true,
    'pinch:mod:out': true,
    'rotate:start': true,
    rotate: true,
    'rotate:end': true,
    'rotate:cw': true,
    'rotate:ccw': true,
    'rotate:mod:start': true,
    'rotate:mod': true,
    'rotate:mod:end': true,
    'rotate:mod:cw': true,
    'rotate:mod:ccw': true,
    'path:start': true,
    path: true,
    'path:end': true,
    'pan:mod:start': true,
    'pan:mod': true,
    'pan:mod:end': true,
    'pressure:change': true,
    wheel: true,
    'wheel:zoom': true
};
